sudo: required
language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ionic' ]; then cd .. && eval "mv $currentfolder generator-ionic" && cd generator-ionic; fi

